version: 2
jobs:
  build:
    docker:
      - image: circleci/golang
    working_directory: /go/src/github.com/vajafari/go-common
    steps:
      - checkout
      - run: go get github.com/stretchr/testify/assert
      - run: go get gopkg.in/mgo.v2
      - run: go get github.com/Gurpartap/logrus-stack
      - run: go get github.com/lestrrat-go/file-rotatelogs
      - run: go get github.com/rifflock/lfshook
      - run: go get github.com/sirupsen/logrus
      - run: go test 